<?php
// Class QueryConceptDistribution will get the distribution of query of the concepts
// It reads a text file generated by b96009
// The file format is shown as followed
// Each line will have some space characters at head of the line.
// Then it will have a number which indicated the number of query of a cluster.
// Then it has a space.
// The cluster name is written at the end of line.
//
// php QueryConceptDistribution.php line.txt > output.csv

class QueryConceptDistribution{
	public $fp;
	public function __construct($file){
		$this->fp = fopen($file, "r");
		if ($this->fp == null){
			printf(STDERR, "%s can't be opened\n", $file);
			exit(-1);
		}
	}
	public function Distribution(){
		$dist = $this->readInputFile();
		foreach ($dist as $num => $value){
			echo $num."\t".$value."\n";
		}
	}
	public function readInputFile(){
		while (!feof($this->fp)){
			$ret = fscanf($this->fp, "%d %s", $num, $cluster);
			if ($ret > 0){
				if (!isset($dist[$num])){
					$dist[$num] = 0;
				}
				$dist[$num] += 1;
			}
		}
		ksort($dist);
		return $dist;
	}
	public function test($filename){
		$obj = new QueryConceptDistribution($filename);
		$obj->Distribution();	
	}
}
QueryConceptDistribution::test($argv[1]);
?>
